"""change default of rate_llimit_retry_count column to 0 x

Revision ID: 0e7955e4906f
Revises: 8d3700470011
Create Date: 2026-01-27 20:49:21.670220

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e7955e4906f"
down_revision: Union[str, Sequence[str], None] = "8d3700470011"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prompt_and_result",
        sa.Column(
            "rate_limit_retry_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prompt_and_result", "rate_limit_retry_count")
    # ### end Alembic commands ###
