"""change default of rate_llimit_retry_count column to 0

Revision ID: 4a7241fc8b84
Revises: fae4a52120c6
Create Date: 2026-01-27 16:39:07.574472

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "4a7241fc8b84"
down_revision: Union[str, Sequence[str], None] = "fae4a52120c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
