"""add openrouter api key col in user table

Revision ID: 75d3c809f45a
Revises: e586bd2f7b08
Create Date: 2026-02-24 14:21:26.849752

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75d3c809f45a"
down_revision: Union[str, Sequence[str], None] = "e586bd2f7b08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_user", sa.Column("api_key_openrouter", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_user", "api_key_openrouter")
    # ### end Alembic commands ###
