"""create tables

Revision ID: 7974cd1c4d44
Revises:
Create Date: 2026-01-11 15:41:50.045457

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7974cd1c4d44"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("otp", sa.String(), nullable=True),
        sa.Column("otp_expire", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_otp_request", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "blacklisted_datasets",
        sa.Column("dataset_id", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("failed_attempts", sa.Integer(), nullable=True),
        sa.Column("last_failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_blacklisted", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("dataset_id"),
    )
    op.create_table(
        "prompt_and_result",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("run_name", sa.String(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("filename", sa.Text(), nullable=True),
        sa.Column("dataset_cols", sa.Text(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("prompt_result", sa.Text(), nullable=True),
        sa.Column("additional_analyses_prompt_result", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("celery_task_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_run",
        sa.Column("request_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("original_common_tasks", sa.Text(), nullable=True),
        sa.Column("common_tasks_w_result", sa.Text(), nullable=True),
        sa.Column("column_transforms_status", sa.String(), nullable=True),
        sa.Column("column_combinations_status", sa.String(), nullable=True),
        sa.Column("columns_info", sa.Text(), nullable=True),
        sa.Column("celery_task_id", sa.String(), nullable=True),
        sa.Column("final_dataset_snippet", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["prompt_and_result.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
        ),
        sa.PrimaryKeyConstraint("request_id", "user_id"),
    )
    op.create_table(
        "user_customized_tasks",
        sa.Column("request_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("saved_tasks_slot_1", sa.Text(), nullable=True),
        sa.Column("saved_tasks_slot_2", sa.Text(), nullable=True),
        sa.Column("saved_tasks_slot_3", sa.Text(), nullable=True),
        sa.Column("imported_original_tasks", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["prompt_and_result.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
        ),
        sa.PrimaryKeyConstraint("request_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_customized_tasks")
    op.drop_table("task_run")
    op.drop_table("prompt_and_result")
    op.drop_table("blacklisted_datasets")
    op.drop_table("app_user")
    # ### end Alembic commands ###
