"""change user_customized_tasks table schema to wide to store different versions

Revision ID: 83706bd3305a
Revises: 9e15e8d1ac57
Create Date: 2025-12-10 15:25:52.617246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83706bd3305a'
down_revision: Union[str, Sequence[str], None] = '9e15e8d1ac57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_customized_tasks', sa.Column('saved_tasks_slot_1', sa.Text(), nullable=True))
    op.add_column('user_customized_tasks', sa.Column('saved_tasks_slot_2', sa.Text(), nullable=True))
    op.add_column('user_customized_tasks', sa.Column('saved_tasks_slot_3', sa.Text(), nullable=True))
    op.add_column('user_customized_tasks', sa.Column('imported_original_tasks', sa.Text(), nullable=True))
    op.drop_column('user_customized_tasks', 'tasks')
    op.drop_column('user_customized_tasks', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_customized_tasks', sa.Column('version', sa.INTEGER(), nullable=True))
    op.add_column('user_customized_tasks', sa.Column('tasks', sa.TEXT(), nullable=True))
    op.drop_column('user_customized_tasks', 'imported_original_tasks')
    op.drop_column('user_customized_tasks', 'saved_tasks_slot_3')
    op.drop_column('user_customized_tasks', 'saved_tasks_slot_2')
    op.drop_column('user_customized_tasks', 'saved_tasks_slot_1')
    # ### end Alembic commands ###
