"""remove rate_limit_retry_count col

Revision ID: 8d3700470011
Revises: ffd654c99dcc
Create Date: 2026-01-27 20:48:55.003636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3700470011'
down_revision: Union[str, Sequence[str], None] = 'ffd654c99dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_and_result', 'rate_limit_retry_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_and_result', sa.Column('rate_limit_retry_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
