"""remove new col

Revision ID: 920dadce2592
Revises: a9e2695151b0
Create Date: 2025-10-24 19:01:40.515451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920dadce2592'
down_revision: Union[str, Sequence[str], None] = 'a9e2695151b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'new_col')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('new_col', sa.TEXT(), server_default=sa.text("'waaaa'"), nullable=True))
    # ### end Alembic commands ###
