"""add last_accessed_at prompt table

Revision ID: b29e701ae23f
Revises: 83706bd3305a
Create Date: 2025-12-15 13:59:17.572955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29e701ae23f'
down_revision: Union[str, Sequence[str], None] = '83706bd3305a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_and_result', sa.Column('last_accessed_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_and_result', 'last_accessed_at')
    # ### end Alembic commands ###
