"""add api key columns to user table

Revision ID: e586bd2f7b08
Revises: 0e7955e4906f
Create Date: 2026-01-30 14:36:59.056168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e586bd2f7b08'
down_revision: Union[str, Sequence[str], None] = '0e7955e4906f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('api_key_cerebras', sa.String(), nullable=True))
    op.add_column('app_user', sa.Column('api_key_google', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'api_key_google')
    op.drop_column('app_user', 'api_key_cerebras')
    # ### end Alembic commands ###
