"""change default of rate_llimit_retry_count column to 0

Revision ID: f33d284d9ac3
Revises: 58252684db95
Create Date: 2026-01-27 16:43:52.844021

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "f33d284d9ac3"
down_revision: Union[str, Sequence[str], None] = "58252684db95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
