"""add rate_limit_retry_count column

Revision ID: fae4a52120c6
Revises: 7974cd1c4d44
Create Date: 2026-01-27 15:48:25.598937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae4a52120c6'
down_revision: Union[str, Sequence[str], None] = '7974cd1c4d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_and_result', sa.Column('rate_limit_retry_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_and_result', 'rate_limit_retry_count')
    # ### end Alembic commands ###
