"""change default of rate_llimit_retry_count column to 0 xxxx

Revision ID: ffd654c99dcc
Revises: f33d284d9ac3
Create Date: 2026-01-27 20:45:04.919061

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "ffd654c99dcc"
down_revision: Union[str, Sequence[str], None] = "f33d284d9ac3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
